#!/bin/bash

output="eDP-1"
brightness=1.0
step=0.1
termsettings=$(stty -g)

stty -echo -icanon time 0 min 1
trap 'stty "$termsettings"; echo; exit' INT TERM

echo
echo -e "  \e[96musage:"
echo "          [+] increment"
echo "          [-] decrement"
echo "          [0] reset"
echo "          [*] quit"
echo

while true; do
    printf "\r\e[3;93mcurrent brightness: \e[0;95m%.1f\e[0m" "$brightness"
    read -r -n 1 key
    case "$key" in
        "=" | "+")
            brightness=$(awk "BEGIN { print $brightness + $step }")
            xrandr --output "$output" --brightness "$brightness"
            ;;
        "-" | "_")
            brightness=$(awk "BEGIN { print $brightness - $step }")
            xrandr --output "$output" --brightness "$brightness"
            ;;
        "0" | ")")
            brightness=1.0
            xrandr --output "$output" --brightness "$brightness"
            ;;
        *)
            break
            ;;
    esac
done

stty "$termsettings"
echo
