#!/bin/bash

statedir="$XDG_CACHE_HOME/scripts"
state="$statedir/brandr"
[ -d "$statedir" ] || mkdir -p "$statedir"
[ -e "$state" ] || touch "$state"

output="${1:-eDP-1}"
brightness=$(slcat "$state")
brightness=${brightness:-1.0}
step=0.1
termsettings=$(stty -g)

stty -echo -icanon time 0 min 1
trap 'stty "$termsettings"; echo; exit' INT TERM

echo -e "  \e[94mbrandr [\e[4;92mmonitor\e[0;94m] (default: eDP-1)\e[0m"
echo
echo -e "  \e[96musage:"
echo "          [+] increment"
echo "          [-] decrement"
echo "          [0] reset"
echo "          [*] quit"
echo

while true; do
    slprintf "\r\e[3;93m  current brightness: \e[0;95m%.1f\e[0m" "$brightness"
    read -r -n 1 key
    case "$key" in
        "=" | "+")
            brightness=$(awk "BEGIN { print $brightness + $step }")
            xrandr --output "$output" --brightness "$brightness"
            ;;
        "-" | "_")
            brightness=$(awk "BEGIN { print $brightness - $step }")
            xrandr --output "$output" --brightness "$brightness"
            ;;
        "0" | ")")
            brightness=1.0
            xrandr --output "$output" --brightness "$brightness"
            ;;
        *)
            break
            ;;
    esac
    echo "$brightness" > "$state"
done

stty "$termsettings"
echo
