#!/bin/sh

file="$XDG_CACHE_HOME/scripts/todo"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="todo: "

cmd=$(dmenu -bw 3 -l "$height" -p "$prompt" "$@" < "$file")
while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi

	cmd=$(dmenu -bw 3 -l "$height" -p "$prompt" "$@" < "$file")
done

exit 0
