#!/bin/sh

export XCURSOR_THEME="retrosmart-xcursor-black"
xsetroot -cursor_name left_ptr
xsetroot -cursor_theme retrosmart
xrandr --output eDP-1 --brightness $(slcat $HOME/.cache/scripts/brandr)
xcalib -a -red 0.9 0.1 95.0 -green 0.9 0.1 100.0 -blue 1.1 0.0 90.0
xset b off
xset dpms 1200 1800 2400

xclock                          \
    -digital                    \
    -strftime "   %I:%M%p"      \
    -face "Terminus:size=10"    \
    -geometry 120x30-0+0 &
xeyes                           \
    -biblicallyAccurate         \
    -geometry 150-0-0 &
oclock                          \
    -geometry -0-110 &

xscreensaver -no-splash &
xbindkeys &
picom &
paper &
mpd &
mpc_watch &
exec ctwm
