#!/bin/sh

found="$(find . -name ".DS_Store" -type f -print)"

confirmer () {
    gum confirm                     \
        --show-output               \
        --timeout=10s               \
        --default "delete?"         \
        --affirmative="yes"         \
        --negative="no"             \
        --prompt.foreground=10      \
        --selected.background=13    \
        --selected.foreground=15    \
        --unselected.background=8   \
        --unselected.foreground=7
 }

[ -z "$found" ]                                 \
    && printf "\033[91mnone found\033[0m\n"     \
    && exit 0

printf "\033[96m$found\033[0m\n\n"

confirmer                                       \
    && find . -name ".DS_Store" -type f -delete \
    || printf "\033[93mskipped deleting\033[0m\n"
