#!/bin/sh

cd "$HOME/Documents/obsidian_vault"
git add .
#git commit -m "[ vaultbackup ][ $(date '+%a_%y%m%d_%I:%M%P') ][ ch_rism_ ]"
git commit -m "$(gessage vaultbackup)"
git pull --rebase
git push

setsid -f herbe " obsidian vault synced with git."
