#!/bin/zsh

setopt prompt_subst

function promptoid() {
    echo "%K{${1}}%F{${2}}${3}%k%f"
}

function promptina() {
    local nl=$'\n'
    local mer=$(date '+%P')
    local clk=$(promptoid 1 0 " %D{%I:%M}${mer} ")
    local zsh=$(promptoid 3 0 " zsh ")
    local me=$(promptoid 4 0 " %n ")
    local us=$(promptoid 5 0 " %m ")

    #local clk=$(promptoid 9 0 " %D{%I:%M}${mer} ")
    #local zsh=$(promptoid 11 0 " zsh ")
    #local me=$(promptoid 12 0 " %n ")
    #local us=$(promptoid 10 0 " %m ")
    echo "${nl}${clk}${zsh}${me}${us}${nl}%F{7}┌── %~${nl}└─%f "
}

PROMPT="$(promptina)"
