#!/bin/zsh

function promptoid() {
    echo "%K{${1}}%F{${2}}${3}%k"
}

function promptina() {
    local nl=$'\n'
    local mer=$(date '+%P')
    local clk=$(promptoid 9 0 " %D{%I:%M}${mer} ")
    local zsh=$(promptoid 11 0 " zsh ")
    local me=$(promptoid 12 0 " %n ")
    local us=$(promptoid 10 0 " %m ")
    echo "${clk}${zsh}${me}${us}${nl}%F{7}┌── %~${nl}└─%f "
}

PROMPT="$(promptina)"
