#!/bin/zsh

function promptoid() {
    echo "%K{${1}}%F{${2}}${3}%k%f"
}

function promptina() {
    local nl=$'\n'
    local mer=$(date '+%p' | tr '[:upper:]' '[:lower:]')

    case "$1" in
        "dark")
            local clk=$(promptoid 0 1 " %D{%I:%M}${mer} ")
            local zsh=$(promptoid 0 2 " zsh ")
            local me=$(promptoid 0 4 " %n ")
            local us=$(promptoid 0 6 " %m ")
            ;;
        "light")
            local clk=$(promptoid 0 9 "[ %D{%I:%M}${mer} ]")
            local zsh=$(promptoid 0 10 "[ zsh ]")
            local me=$(promptoid 0 12 "[ %n ]")
            local us=$(promptoid 0 14 "[ %m ]")
            ;;
    esac

    echo "${nl}${clk}${zsh}${me}${us}${nl}%F{7}┌── %~${nl}└─%f "
}

PROMPT="$(promptina light)"
