#!/bin/sh

find . -type f -printf '%T@ %p\n'   \
    | sort -n                       \
    | cut -d' ' -f2-                \
    | tac                           \
    | dmenu -i -p "recents:"        \
    | xargs -r nvim
