#!/bin/sh

style () {
    local text="$1"
    local brdr="$2"
    shift 2
    gum style                           \
        --foreground="$text"            \
        --border="rounded"              \
        --border-foreground="$brdr"     \
        "$@"
}

VOIDATA="$HOME/Documents/void"

style 10 11 "  updating void linux  "

style 13 12 "backing up package list..."
xpkg -m > $VOIDATA/pkglist.txt

style 12 11 "running full system upgrade..."
doas xbps-install -Su

style 11 10 "cleaning orphaned packages..."
doas xbps-remove -o

style 10 9 "updating source tree..."
cd $HOME/.local/share/void-packages
git checkout master
git pull upstream master

setsid -f herbe "  void updated.  "

echo

while true; do
    choice=$(
        gum choose                                                      \
            --header="update lanugage build system packages?"           \
            --cursor="- "                                               \
            --header.foreground=10                                      \
            --cursor.foreground=9                                       \
            --item.foreground=13                                        \
            "yes" "no" "py" "rs" "go"
        )
    case "$choice" in
        yes)
            style 14 9 "beginning language package updater."
            sleep 1

            style 13 12 "updating python packages with pipx:"
            pipx upgrade-all

            style 12 11 "updating rust packages with cargo:"
            cargo install-update -a

            style 11 10 "updating go packages with gup:"
            gup update

            style 14 9 "language packages updated."
            break
            ;;
        no)
            style 10 11 "skipped lang packages update."
            break
            ;;
        py)
            style 13 12 "updating python packages with pipx:"
            pipx upgrade-all
            style 14 9 "python packages updated."
            break
            ;;
        rs)
            style 12 11 "updating rust packages with cargo:"
            cargo install-update -a
            style 14 9 "rust packages updated."
            break
            ;;
        go)
            style 11 10 "updating go packages with gup:"
            gup update
            style 14 9 "go packages updated."
            break
            ;;
        *)
            style 7 8 "invalid response."
            ;;
    esac
done
