#!/bin/sh

killall -q xclock
killall -q xeyes
killall -q oclock

case "$1" in
    "ctwm")
        #                               ctwm
        xclock                          \
            -digital                    \
            -strftime "   %I:%M%p"      \
            -face "Terminus:size=10"    \
            -geometry 120x30-0+0 &
        xeyes                           \
            -biblicallyAccurate         \
            -geometry 150-0-0 &
        oclock                          \
            -geometry -0-110 &
        ;;
    *)
        #                               fvwm
        xclock                          \
            -digital                    \
            -strftime "%I:%M  %p"       \
            -face "Terminus:size=10"    \
            -geometry 86x30-2+90 &
        xeyes                           \
            -biblicallyAccurate         \
            -geometry 150-0-0 &
        oclock                          \
            -geometry 90x90-8+140 &
        ;;
esac
