#!/bin/sh

killall -q xclock
killall -q xeyes
killall -q oclock

xclock                          \
    -digital                    \
    -strftime "   %I:%M%p"      \
    -face "Terminus:size=10"    \
    -geometry 120x30-0+0 &
xeyes                           \
    -biblicallyAccurate         \
    -geometry 150-0-0 &
oclock                          \
    -geometry -0-110 &
